# version: '3'

services:
    app:
      image: ahmedelenany703/count-app:v1.0.0
      ports:
        - "3000:3000"
      depends_on: 
        - redis
    
    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"